# This is a basic workflow to help you get started with Actions

name: Update Issues List

on:
 issues:
    types: [opened, edited, closed, deleted]
    
permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update-issues:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - name: checkout
       uses: actions/checkout@v2
       with:
         repository: Diego-Brocanelli/issues-lis-readme
         path: main
     - name: rewriteReadme
       uses: seed-of-apricot/issue-list-readme@v1.1.0
       with:
         GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
         pattern: '<!-- issueTable -->' # suffixing "Demo" for this readme
         labels: 'idea'
         state: 'open'
