# This is a basic workflow to help you get started with Actions

name: Update Issues List

on:
 issues:
    types: [opened, edited, closed, deleted]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update-issues:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Auto Issue List in README
      # You may pin to the exact commit or the version.
      # uses: seed-of-apricot/issue-list-readme@55669b219cbd65d46522bd6dde3067b8d1df3c5f
      uses: seed-of-apricot/issue-list-readme@v1.1.0
      with:
        # token
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        # pattern to detect the place to locate the table
        pattern: '<!-- issueTable -->'
        # comma-separated labels to filter the issues
        labels: 'idea'
        # state of the issues to filter them (open or closed)
        state: 'open'
