# This is a basic workflow to help you get started with Actions

name: Update Issues List

on:
 issues:
    types: [opened, edited, closed, deleted]
    
permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update-issues:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: rewriteReadme
        uses: Diego-Brocanelli/issues-lis-readme@main
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          pattern: "<!-- issueTableDemo -->"
          labels: "idea"
          state: "open"
      - name: add-and-commit
        uses: EndBug/add-and-commit@v4
        with:
          message: README.md has been re-written
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
